# Generated by Django 4.1.3 on 2023-10-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='alergies',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
